spring:
  application:
    name: ecommerce-api-rest
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 5MB
  cache:
    type: simple

app:
  uploads:
    products:
      image-path: uploads/products